"""AgentContract: reliability primitives for long-horizon tool-using agents."""

from agentcontract.common.immutable import FrozenDict
from agentcontract.constraints import (
    Constraint,
    ConstraintLedger,
    ConstraintProvenance,
    ConstraintScope,
    ConstraintSource,
    ConstraintStatus,
    ConstraintStrength,
    RuleEffect,
)
from agentcontract.evidence import (
    Claim,
    ClaimEvaluation,
    ClaimNotFoundError,
    ClaimType,
    ClaimVerdict,
    EvidenceError,
    EvidenceGate,
    EvidenceGraph,
    EvidenceRef,
    EvidenceRelation,
    EvidenceValidationError,
)
from agentcontract.guard import (
    Action,
    ActionKind,
    ActionObservation,
    DecisionKind,
    GuardDecision,
    GuardError,
    GuardValidationError,
    SpecGuard,
    match_scope,
)
from agentcontract.runtime import (
    AgentContractRuntime,
    AgentContractRuntimeError,
    IdGenerator,
    RuntimeExecutionResult,
    RuntimeValidationError,
    ToolExecutionError,
    ToolExecutionOutcome,
    ToolExecutor,
    VerificationResult,
)
from agentcontract.trace import (
    ActorKind,
    EventKind,
    ToolCall,
    ToolResult,
    ToolResultStatus,
    TraceDurableValue,
    TraceEvent,
    TracePointer,
    TraceStore,
)

from agentcontract.extraction import (
    ClaimDraft,
    ClaimExtractor,
    ClientExtractionError,
    ConstraintDraft,
    ConstraintScopeDraft,
    DiagnosticSeverity,
    ExtractionDiagnostic,
    ExtractionError,
    ExtractionRequest,
    ExtractionResult,
    ExtractionValidationError,
    FakeStructuredExtractionClient,
    RequirementExtractor,
    StructuredExtractionClient,
    extract_and_verify_claims,
    get_claim_extraction_schema,
    get_requirement_extraction_schema,
)
from agentcontract.benchmark import (
    ALL_STANDARD_SCENARIOS,
    BenchmarkMetrics,
    BenchmarkReport,
    BenchmarkRunner,
    BenchmarkScenario,
    BenchmarkVariant,
    ScenarioExecutionRecord,
    ScenarioResult,
    ScriptedAction,
    get_standard_scenarios,
)
from agentcontract.adapters import (
    AdapterConfigurationError,
    AdapterError,
    AdapterValidationError,
    ExternalToolCallRecord,
    ExternalToolResultRecord,
    OTelSpan,
    OTelTraceBridge,
    OTelTraceExport,
    OpenAICompatibleExtractionClient,
    ToolEventAdapter,
    get_openai_claim_extraction_schema,
    get_openai_requirement_extraction_schema,
    to_otlp_span_id,
    to_otlp_trace_id,
    to_strict_json_schema,
    validate_strict_json_schema,
)

__version__ = "0.1.0"

__all__ = [
    # Common
    "FrozenDict",
    # Constraints
    "Constraint",
    "ConstraintLedger",
    "ConstraintProvenance",
    "ConstraintScope",
    "ConstraintSource",
    "ConstraintStatus",
    "ConstraintStrength",
    "RuleEffect",
    # Guard
    "Action",
    "ActionKind",
    "ActionObservation",
    "DecisionKind",
    "GuardDecision",
    "GuardError",
    "GuardValidationError",
    "SpecGuard",
    "match_scope",
    # Trace
    "ActorKind",
    "EventKind",
    "ToolCall",
    "ToolResult",
    "ToolResultStatus",
    "TraceDurableValue",
    "TraceEvent",
    "TracePointer",
    "TraceStore",
    # Evidence
    "Claim",
    "ClaimEvaluation",
    "ClaimNotFoundError",
    "ClaimType",
    "ClaimVerdict",
    "EvidenceError",
    "EvidenceGate",
    "EvidenceGraph",
    "EvidenceRef",
    "EvidenceRelation",
    "EvidenceValidationError",
    # Runtime
    "AgentContractRuntime",
    "AgentContractRuntimeError",
    "IdGenerator",
    "RuntimeExecutionResult",
    "RuntimeValidationError",
    "ToolExecutionError",
    "ToolExecutionOutcome",
    "ToolExecutor",
    "VerificationResult",
    # Extraction
    "ClaimDraft",
    "ClaimExtractor",
    "ClientExtractionError",
    "ConstraintDraft",
    "ConstraintScopeDraft",
    "DiagnosticSeverity",
    "ExtractionDiagnostic",
    "ExtractionError",
    "ExtractionRequest",
    "ExtractionResult",
    "ExtractionValidationError",
    "FakeStructuredExtractionClient",
    "RequirementExtractor",
    "StructuredExtractionClient",
    "extract_and_verify_claims",
    "get_claim_extraction_schema",
    "get_requirement_extraction_schema",
    # Benchmark
    "ALL_STANDARD_SCENARIOS",
    "BenchmarkMetrics",
    "BenchmarkReport",
    "BenchmarkRunner",
    "BenchmarkScenario",
    "BenchmarkVariant",
    "ScenarioExecutionRecord",
    "ScenarioResult",
    "ScriptedAction",
    "get_standard_scenarios",
    # Adapters
    "AdapterConfigurationError",
    "AdapterError",
    "AdapterValidationError",
    "ExternalToolCallRecord",
    "ExternalToolResultRecord",
    "OTelSpan",
    "OTelTraceBridge",
    "OTelTraceExport",
    "OpenAICompatibleExtractionClient",
    "ToolEventAdapter",
    "get_openai_claim_extraction_schema",
    "get_openai_requirement_extraction_schema",
    "to_otlp_span_id",
    "to_otlp_trace_id",
    "to_strict_json_schema",
    "validate_strict_json_schema",
    # Meta
    "__version__",
]


